# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
# Copyright (C) 2020 Northwestern University.
#
# Invenio-RDM-Records is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: master
  pull_request:
    branches:
      - master
      - "maint-**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        db-service: [postgresql13]
        search-service: [opensearch2,elasticsearch7]

    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: ${{ github.event.inputs.extras || 'tests' }}${{ matrix.search-service && ',' || '' }}${{ matrix.search-service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Pre-install
        uses: ./.github/actions/pre-install
        if: ${{ hashFiles('.github/actions/pre-install/action.yml') != '' }}

      - name: Install dependencies
        run: |
          pip install ".[$EXTRAS]"
          pip freeze
          docker version

      - name: Run tests
        run: ./run-tests.sh
